import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const links = [
    { href: '/', label: 'Home' },
    { href: '/question1', label: 'Question1' },
    { href: '/question2', label: 'Question2' },
    { href: '/question3', label: 'Question3' },
    { href: '/question4', label: 'Question4' },
    { href: '/question5', label: 'Question5' },
    { href: '/question6', label: 'Question6' },
    { href: '/question7', label: 'Question7' },
    { href: '/blog', label: 'Blog' },
  ]

  return (
    <html lang="en">
      <body className={inter.className}>
      <header className="mb-20">
          <nav>
            <ul className="flex items-center">
              {links.map(({ href, label }) => (
                <li key={href} className="px-4 text-2xl">
                  <Link href={href}>{label}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
